### ISSUE TITLE
Provide Dockerfile

### ISSUE THREAD

**Issue by nilsmelchert** [aau-cns/poet#14]
I wanted to ask if it would be possible to add the Dockerfile to this repository to better track how it is built and make adjustments if necessary.

**Comment by tgjantos** [comment]
Good idea! I will add the Dockerfile and the necessary additional commands over the weekend / beginning of next week.

Best,
Thomas

**Comment by tgjantos** [comment]
Dear @nilsmelchert,

please checkout the most recent commit. I added the Dockerfile and the building instructions. Note that deformable_attention is by default not part of PyTorch and needs to be installed separately. I described the necessary steps [here](https://github.com/aau-cns/poet/blob/main/docker/README.md).

Hope this helps you!

Best,
Thomas

**Comment by tgjantos** [comment]
That would be quite convenient!

**Comment by tgjantos** [comment]
Closed due to inactivity. Feel free to open issue again.
