### ISSUE TITLE
Question about two missing parameter files in main.py

### ISSUE THREAD

**Issue by JimmyMotley** [aau-cns/poet#2]
# main.py
<img width="653" alt="image" src="https://user-images.githubusercontent.com/92315177/209754054-f231d6cb-1ed7-44c1-80f7-a688a6c95197.png">
line 138: '--class_info', 'annotations/classes.json'

line 142: '--model_symmetry', '/annotations/symmetries.json'

I have tried to find the two missing .json files but failed, could you please provide them or the method to get these files? Thanks a lot!

**Comment by tgjantos** [comment]
Thank you for pointing out that these files are missing. We will add example files for the YCB-V and LM-O dataset.

Best,
Thomas
