### ISSUE TITLE
Link to Supplementary Material

### ISSUE THREAD

**Issue by retazo0018** [aau-cns/poet#25]
Hi @tgjantos,

Thanks for the amazing work. 

Is there an online link to the mentioned supplementary material anywhere?

Thanks,

**Comment by tgjantos** [comment]
Hi @retazo0018,

thank you for your interest in PoET! Sure the supplementary material can be found here:
https://www.aau.at/wp-content/uploads/2022/09/jantos_poet.pdf

Hope this helps you!

Best,
Thomas

**Comment by retazo0018** [comment]
Thank you!
