### ISSUE TITLE
Details about training ycbv with yolo

### ISSUE THREAD

**Issue by HannahHaensen** [aau-cns/poet#4]
Thanks for the nice work, could you provide some details about training ycbv with real and synthetic data.

did you first train on synthetic and then on real or both together?
and if so have you adapted the annotations file and merged them?

**Comment by tgjantos** [comment]
Hi!

We train PoET simultaneously with real and synthetic data. We create a dedicated annotation file that contains the annotation both for real as well as synthetic data. Checkout the [ycbv2poet.py](https://github.com/aau-cns/poet/blob/main/data_utils/data_annotation/ycbv2poet.py) annotation script. This allows you to create a annotation file that contains real as well as simulated data. Hope this answers your question!

Best,
Thomas

**Comment by tgjantos** [comment]
Closed due to inactivity.
