### ISSUE TITLE
fail to pull docker images

### ISSUE THREAD

**Issue by SoraCaptain** [aau-cns/poet#5]
Hello~
        There is below error while pulling the provided docker image

        Error response from daemon: Get https://gitlab.aau.at:5050/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
 
        Could you please provide other docker image link?
        Thanks a lot!

**Comment by tgjantos** [comment]
Hello,

sorry for the inconvenience caused by the Docker image link. We added an alternative Docker image in the README. Please try out the new image.

```ssh
docker pull aaucns/poet:latest
```
Best,
Thomas

**Comment by SoraCaptain** [comment]
Hello~
        It works now. Thanks for help!
