### ISSUE TITLE
Questions about visualization or demo script

### ISSUE THREAD

**Issue by lishiyu0088** [aau-cns/poet#7]
Dear authors,

Thank you for sharing this nice work and releasing this code for open source. I just wonder if there are scripts for visualization for 6Dpose with 3D bounding boxes or prediction masks as shown in the paper as follow.
![image](https://user-images.githubusercontent.com/65619737/220137300-ebfe2593-ae39-4d6e-9310-0ae83c598d11.png)

Best regards

**Comment by tgjantos** [comment]
Closed due to inactivity.
